In [1]:
#starting numpy


In [3]:
# Numpy becuase its faster, more space efficient and more functional

In [7]:
import numpy as np
a = np.arange(9,50)
print(a)

[ 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32
 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


In [11]:
import numpy as np
a = np.eye(5,6)
a

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.]])

In [13]:
import numpy as np
a = np.linspace(0,5,10)
a

array([0.        , 0.55555556, 1.11111111, 1.66666667, 2.22222222,
       2.77777778, 3.33333333, 3.88888889, 4.44444444, 5.        ])

In [38]:
import numpy as np
a = [[1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15],[16,17,18,19,20]]
a = np.array(a)
print(a[2,:3])
print(a[1:4,3])
print(a[2:4])
print(a[1:3,1:3])

[11 12 13]
[ 9 14 19]
[[11 12 13 14 15]
 [16 17 18 19 20]]
[[ 7  8]
 [12 13]]


In [1]:
#Mathematical Operations

In [2]:
#Findin Indices of the non zero elements fromt he following array

In [5]:
import numpy as np
a = np.array([1,2,0,0,4,0])
arr = np.where(a == 0)
print(arr)

(array([2, 3, 5], dtype=int64),)


In [11]:
b = np.array([1,3,5,7,9,11,13,15,17,19])
a = np.where(b%3==0)
for i in a:
    print(i)

[1 4 7]


In [20]:
b = np.arange(1,11)
a = np.where((b%2)!=0)
b[a] = -1
b

array([-1,  2, -1,  4, -1,  6, -1,  8, -1, 10])

In [32]:
a = np.random.randint(0,20,10)
print(a)
b = np.argmax(a)
a[b] = 0
print(a)

[ 6 14  1  3  2  5 13  5 15  3]
[ 6 14  1  3  2  5 13  5  0  3]


In [54]:
#negate elemenets between 3 and 8 both inclusive
a = np.arange(1,11)
b = a[(a<3) | (a>8)]
b

array([ 1,  2,  9, 10])

In [102]:
#print age w height of ppl taller than 155cm
a = np.random.randint(15,25,20)
b = np.random.randint(145,165,20)
c = np.array(np.where(b>155))
print(a)
print(b)
for i in c[0]:
    print(f'{a[i]} -- {b[i]}')

[16 16 20 21 15 16 21 21 19 15 17 22 16 19 18 20 16 22 21 23]
[145 153 163 162 157 149 153 161 155 153 159 164 160 156 153 149 148 160
 152 162]
20 -- 163
21 -- 162
15 -- 157
21 -- 161
17 -- 159
22 -- 164
16 -- 160
19 -- 156
22 -- 160
23 -- 162


In [113]:
### HOW TO MAKE A 2D ARRAY
import numpy as np
a = np.arange(20).reshape(4,5)
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [7]:
import numpy as np
a = np.arange(20,40).reshape(4,5)
print(a)
ans = []
m = 0
for k in range(4):
    for i in a[:,1]:
        m = max(m,i)
    for i in a:
        if m in a:
            ans.append(i)
            a.pop(i)
            break
print(ans)

[[20 21 22 23 24]
 [25 26 27 28 29]
 [30 31 32 33 34]
 [35 36 37 38 39]]


AttributeError: 'numpy.ndarray' object has no attribute 'pop'